inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'bin/*'

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 20
  Exclude:
   - 'app/decorators/*json_decorator.rb'
